Iter15
Archetarcher/metrics pull request #15
Opened 2024-08-27 18:06 UTC by Archetarcher

2024-08-30 17:24 UTC, tmvrus requested changes
есть вопросы

2024-08-30 17:24 UTC, tmvrus commented on cmd/server/main.go
> +	}
а можно ли продолжать работу если вернулась ошибка?

2024-08-30 17:24 UTC, tmvrus commented on cmd/server/main.go
> +		logger.Log.Error("failed with error", zap.String("error", err.Text), zap.Int("code", err.Code))
и тут тоже

2024-08-30 17:24 UTC, tmvrus commented on internal/agent/compression/gzip.go
> +		zb := gzip.NewWriter(buf)
довольно странно, если условие `!= "gzip"` то мы используем модуль `gzip`

2024-08-30 17:24 UTC, tmvrus commented on internal/agent/domain/models.go
> +// Gauge strict
strict?

2024-08-30 17:24 UTC, tmvrus commented on internal/server/handlers/metrics_handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
вместо `context.Background()` тут можно использовать контекст входящего запроса `r.Context()`

2024-08-30 17:24 UTC, tmvrus commented on internal/server/handlers/metrics_handler.go
> +	db, err := sql.Open("pgx", h.config.Store.Pgx.DatabaseDsn)
каждый запрос к Ping будет создавать новое подключение к базе данных, рекомендую хотя бы закрывать его после выполнения Ping

2024-08-30 17:24 UTC, tmvrus commented on internal/server/handlers/metrics_handler.go
> +func validateUpdatesRequest(r *http.Request) (*[]domain.Metrics, *domain.MetricsError) {
нет большого смысла  возвращать список по ссылке `*[]domain.Metrics, ` поскольку он сам по себе ссылочный тип

2024-08-30 17:24 UTC, tmvrus commented on internal/server/services/metrics_service.go
> +	response, _ = s.repo.Get(request)
а почему игнорируются возможные ошибки?

2024-08-30 17:24 UTC, tmvrus commented on internal/server/store/pgx/store.go
> +		return nil, handleDBError(err, http.StatusInternalServerError)
вот такой подход называется "abstraction leak" зачем слою хранения знать о том, что общение осуществляется через http? а если будет две версии api? а если слой хранения вообще работает в составе cli-утилиты

2024-08-30 17:24 UTC, tmvrus commented on internal/server/repositories/metric_repository.go
> +	CheckConnection() *domain.MetricsError
довольно странно что интерфейс хранилища не подразумевает передачу контекста из входящего запроса, из-за этого внутри приходится использовать context.Background а по хорошему такой контекст должен быть вообще один на все приложение.

2024-09-01 09:51 UTC, Archetarcher commented on cmd/server/main.go
> +	}
поправила

2024-09-01 09:51 UTC, Archetarcher commented on cmd/server/main.go
> +		logger.Log.Error("failed with error", zap.String("error", err.Text), zap.Int("code", err.Code))
поправила

2024-09-01 09:53 UTC, Archetarcher commented on internal/agent/compression/gzip.go
> +		zb := gzip.NewWriter(buf)
по какой-то причине resty запускает middleware, onBeforeRequest несколько раз, поэтому без этого условия  происходит шифрование зашифрованного тела, не смогла найти как убрать цикл запуска middleware, добавила условие не шифровать если есть заголовок и тело уже зашифрованное

2024-09-01 09:54 UTC, Archetarcher commented on internal/agent/domain/models.go
> +// Gauge strict
поправила

2024-09-01 09:55 UTC, Archetarcher commented on internal/server/handlers/metrics_handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
поняла, поправила

2024-09-01 10:05 UTC, Archetarcher commented on internal/server/handlers/metrics_handler.go
> +	db, err := sql.Open("pgx", h.config.Store.Pgx.DatabaseDsn)
поправила

2024-09-01 10:14 UTC, Archetarcher commented on internal/server/handlers/metrics_handler.go
> +func validateUpdatesRequest(r *http.Request) (*[]domain.Metrics, *domain.MetricsError) {
поправила

2024-09-01 10:17 UTC, Archetarcher commented on internal/server/services/metrics_service.go
> +	response, _ = s.repo.Get(request)
поправила

2024-09-01 10:25 UTC, Archetarcher commented on internal/server/store/pgx/store.go
> +		return nil, handleDBError(err, http.StatusInternalServerError)
поправила

2024-09-01 11:06 UTC, Archetarcher commented on internal/server/repositories/metric_repository.go
> +	CheckConnection() *domain.MetricsError
поправила

2024-09-02 08:44 UTC, tmvrus approved these changes

2024-09-09 10:04 UTC, merged